### ISSUE TITLE
Не показывать внутренние поля классов

### ISSUE THREAD

**Issue by AIexandrKotov** [NETMouse-projects/NETSquirrel#43]
```pas
{$reference NETSquirrel.dll}
uses System.Reflection;
 
type
  Some = class
    public auto property X: integer;
  end;
 
begin
  (new Some()).AutoPrintLine(BindingFlags.Instance or BindingFlags.NonPublic, ', ');
end.
```
```
#PField1 = 0
```

**Comment by MrFresnel** [comment]
Стоит сказать, что изначально планировалось, что и "детали реализации" будут видны через `AutoPrintLine` и ему подобные методы. Лучшим решением, на мой взгляд, будет введение дополнительного параметра, указывающего включать ли подобные вещи в вывод или нет.

**Comment by Alvin-Seville** [comment]
Обнаружилась проблема, благодаря которой, фильтрация специальных членов классов и записей в PascalABC.NET не будет работать через свойство `IsSpecialName`:
```
uses System.Reflection;

type
  T = class
  public
    auto property X: integer;
  end;

begin
  (new T()).GetType().GetFields(BindingFlags.NonPublic or BindingFlags.Instance)
    .Where(x -> x.IsSpecialName).Println();
end.
```
