### ISSUE TITLE
Выдавать null вместо пустоты при нулевой ссылке

### ISSUE THREAD

**Issue by AIexandrKotov** [NETMouse-projects/NETSquirrel#44]
```pas
{$reference NETSquirrel.dll}
uses System.Reflection;
 
type
  Some = class
    public auto property X: Action<integer> := nil;
  end;
 
begin
  (new Some()).AutoPrintLine(BindingFlags.Instance or BindingFlags.Public, ', ');
end.
```
```
X = 
```

**Comment by MrFresnel** [comment]
Да, выдавать `null` - это действительно хорошее и наглядное решение показать `пустую ссылку`. Надо проработать весь проект, чтобы везде на этот счёт был одинаковый вывод.

**Comment by Alvin-Seville** [comment]
Проблема, описанная ниже, не является критической, но она существует. Не во всех языках нулевая ссылка обозначается как `null`, поэтому, если вывод будет таких ссылок будет осуществляться посредством `null`, то нарушится совместимость с языками, в которых нулевая ссылка обозначается не `null`.
