### ISSUE TITLE
Introduce T[] GenerateArray<T>(int count, Func<T[], int, T> selector) 

### ISSUE THREAD

**Issue by MrFresnel** [NETMouse-projects/NETSquirrel#47]
![image](https://user-images.githubusercontent.com/42812113/65893582-d6dbf780-e3b0-11e9-90d9-cca7f090d1ea.png)

Idea's author: [Pavel314](https://github.com/Pavel314).

**Comment by Pavel314** [comment]
Возможно, стоит передавать массив  в качестве списка, доступным только на чтение.  Передача  коллекции в виде массива позволяет произвести модификацию с его элементами, что нарушает основную идеологию метода GenerateArray, так как только он должен иметь право записи. С другой стороны, способ передачи в виде массива добавляет существенную гибкость.  
Приблизительная реализация:
```
public static T[] GenerateArray<T>(int count, Func<int,IReadOnlyList<T>,T> selector, int firstIndex){
	//check arguments
	T[] source=new T[count];
	for (int i=0;i<count;i++){
		source[i]=selector(i+firstIndex,source);
	}
	return source;
}
```

**Comment by MrFresnel** [comment]
В NETSquirrel я стараюсь придерживаться правила: меньше входных ограничений, меньше выходных. Под этим имеется ввиду следующее: я подаю входным параметром наиболее обобщённый тип, но получаю менее обобщённый, специализированный под конкретные задачи. Говоря об этой задаче, я всё-таки склонен к параметру типа массив.
