### ISSUE TITLE
PrintBy - уязвима

### ISSUE THREAD

**Issue by Pavel314** [NETMouse-projects/NETSquirrel#57]
Текущая реализация [PrintBy](https://github.com/NETMouse-projects/NETSquirrel/blob/master/NETSquirrel/Extensions/IEnumerableExtensions.cs) содержит две серьёзные ошибки:

1. Для последовательности(`IEnumerable`) применять метод `.ToArray()` может привести к фатальной ошибки времени выполнения, если последовательность является генератором бесконечного ряда(т.е. `yields`) или же ряда, число элементов которого выйдет за допустимый диапазон индексации массива.
2. Для добавления разделителей при выводе, использовать преобразование к массиву и индексы вовсе не обязательно, эту проблему можно решить иным, более эффективным путём. Условная демонстрация данного подхода:
```
        public static IEnumerable<T> PrintBy<T, TOutput>(this IEnumerable<T> collection, Func<T, TOutput> selector)
        {
            bool isf = true;//isf - isFirst
            foreach(T item in collection)
            {
                if (!isf)
                {
                    Console.Write(", ");
                } else
                isf = false;
                Console.Write(selector(item));
            }
            return collection;
        }
    }
```
Если эффективность имеет приоритет многократно превышающий читаемость кода, то:
<details>
  <summary>Код</summary>

```csharp
        public static IEnumerable<T> PrintBy<T, TOutput>(this IEnumerable<T> collection, Func<T, TOutput> selector)
        {
            if (collection is null)
                return collection;

            IEnumerator<T> enumerator = collection.GetEnumerator();
            if (enumerator is null || !enumerator.MoveNext())
                return collection;

            Console.Write(selector(enumerator.Current));

            while (enumerator.MoveNext())
            {
                Console.Write("{0}{1}",", ",selector(enumerator.Current));
            }
            return collection;
        }
```
</details>

**Comment by MrFresnel** [comment]
Эффективность - одно из важных параметров, под которые оптимизируется библиотека.
